on: 
  issues:
    types:
      - opened
      - reopened

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Set Issue Bug type
      if: contains(github.event.issue.labels.*.name, 'bug') == true
      run: echo "ISSUE_TYPE=Bug" >> $GITHUB_ENV
      
    - name: Set Issue Task type
      if: contains(github.event.issue.labels.*.name, 'bug') == false
      run: echo "ISSUE_TYPE=Task" >> $GITHUB_ENV

    - name: Create issue
      if: contains(github.event.issue.labels.*.name, 'from jira') == false
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: A3MS
        issuetype: ${{ env.ISSUE_TYPE }}
        summary: git_webhook) ${{ github.event.issue.title }}
        description: ${{ github.event.issue.body }}
        
    - name: Log created issue
      if: contains(github.event.issue.labels.*.name, 'from jira') == false
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
    
#     - name: Create comment
#       if: contains(github.event.issue.labels.*.name, 'from jira') == false
#       uses: peter-evans/create-or-update-comment@v2
#       with:
#         issue-number: ${{ github.event.issue.number }}
#         body: |
#           Created a Jira issue with ${{ steps.create.outputs.issue }}
          
    - name: Comment to JIRA
      uses: atlassian/gajira-comment@master
      with:
        issue: ${{ steps.create.outputs.issue }}
        comment: Git ticket num-${{ github.event.issue.number }} by git_webhook
          
    - name: Update issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'update-issue'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        title: ${{ steps.create.outputs.issue }} ${{ github.event.issue.title }}
