on: 
  issues:
    types:
      - opened
      - reopened

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Bug issue
      id: create-bug-issue
      if: contains(github.event.pull_request.labels.*.name, 'tttt')
      run: |
        echo "${{ github.event.issue.labels.*.name }}"
#       uses: atlassian/gajira-create@master
#       with:
#         project: A3MS
#         issuetype: Bug
#         summary: ${{ github.event.issue.title }}
#         description: ${{ github.event.issue.body }}
        
#     - name: Create Task issue
#       id: create-task-issue
#       if: ${{ github.event.issue.labels.name }} != "bug"
#       uses: atlassian/gajira-create@master
#       with:
#         project: A3MS
#         issuetype: Task
#         summary: ${{ github.event.issue.title }}
#         description: ${{ github.event.issue.body }}
        
#     - name: Log created issue
#       run: echo "Issue ${{ steps.create.outputs.issue }} was created"
    
#     - name: Create comment
#       uses: peter-evans/create-or-update-comment@v2
#       with:
#         issue-number: ${{ github.event.issue.number }}
#         body: |
#           Created a Jira issue with ${{ steps.create.outputs.issue }}
