on: 
  issues:
    types:
      - opened

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira issue
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: A3MS
        issuetype: Task
        summary: Issue created from ${{ github.event.issue.title }}
        description: ${{ github.event.issue.body }}
        
    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
